#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export GOPATH="$shome"
  go get -u github.com/GetStream/vg
}

main "$@"
