#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.vg')" != "$VG_VERSION" ]]; then
    return 1
  fi

  case "${DISTRIB_ID}" in
    Darwin|Ubuntu)
      if ! type -P bindfs >/dev/null; then
        return 1
      fi
      ;;
  esac

  return 0
}

main "$@"
