#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_vg="0.0.1"
  jq -n --arg vg "$ver_vg" '{vg: $vg}'
}

version "$@"
